---
name: CI on default branch

on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  commit-dist:
    runs-on: ['ubuntu-latest'] 
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - shell: bash
        run: |
          npm install
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            sha256=$(make dist-checksum)
            echo "::notice:: 'dist' sha256sum: $sha256"
            printf "" > .gitignore 
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add dist
            git commit -m "$(printf "build(dist): $(echo $sha256 | awk '{print substr($1, 1, 7)}') \n\nsha256sum: $sha256")"
            git push
          fi

  compute-tag:
    runs-on: ['ubuntu-latest'] 
    timeout-minutes: 5
    needs: 
      - commit-dist

    outputs:
      tag: ${{ steps.run_action.outputs.tag }}
      previous-tag: ${{ steps.run_action.outputs.previous-tag }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          
      - uses: actions/checkout@v4
        with:
          path: git-next-tag

      - uses: ./git-next-tag/
        id: run_action
        with:
          tag-prefix: v

  release-draft:
    if: always() && (needs.compute-tag.outputs.tag != '')
    runs-on: ['ubuntu-latest'] 
    timeout-minutes: 5
    needs: 
      - commit-dist
      - compute-tag

    outputs:
      release-tag-ref: ${{ steps.release.outputs.release-tag-ref }}

    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: ./.github/actions/draft-release/
        id: release
        with:
          tag: ${{ needs.compute-tag.outputs.tag }}
          old-tag: ${{ needs.compute-tag.outputs.previous-tag }}
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: echo "Draft release created at ${{ steps.release.outputs.release-tag-ref || 'N/A' }}"
