---
name: Tests

on:
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tests.yml'

concurrency:
    group: ci-tests-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:  
  action-tests:
    runs-on: ['ubuntu-latest']
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - shell: bash
        run: 
          npm install

      - uses: ./
        id: run_action
        with:
          tag-prefix: v
      
      - shell: bash
        run: echo "${{ steps.run_action.outputs.tag }}"
